FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код проекта
COPY . .

# Открываем порт для FastAPI
EXPOSE 8000

ENV PYTHONPATH=/app

# Команда для запуска (берем из твоего Readme.md)
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]